<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\GatewayService.Application.Helpers\GatewayService.Application.Helpers.csproj" />
      <ProjectReference Include="..\GatewayService.Domain.Exceptions\GatewayService.Domain.Exceptions.csproj" />
      <ProjectReference Include="..\GatewayService.Domain.Interfaces\GatewayService.Domain.Interfaces.csproj" />
    </ItemGroup>

</Project>
