apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: test
data:
  04-init.sql: |
    CREATE TABLE IF NOT EXISTS reservations
    CREATE TABLE IF NOT EXISTS libraries
    CREATE TABLE IF NOT EXISTS ratings