<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.14" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.13"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.20">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\RatingSystem.Application.Jobs\RatingSystem.Application.Jobs.csproj" />
      <ProjectReference Include="..\RatingSystem.Application.Services\RatingSystem.Application.Services.csproj" />
      <ProjectReference Include="..\RatingSystem.DataAccess.Context\RatingSystem.DataAccess.Context.csproj" />
      <ProjectReference Include="..\RatingSystem.DataAccess.Repositories\RatingSystem.DataAccess.Repositories.csproj" />
      <ProjectReference Include="..\RatingSystem.Domain.Interfaces\RatingSystem.Domain.Interfaces.csproj" />
      <ProjectReference Include="..\RatingSystem.Web.Dto\RatingSystem.Web.Dto.csproj" />
    </ItemGroup>

</Project>
